# Generated by Django 5.2.14 on 2026-06-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitation_role_alter_user_role_staffprofile'),
        ('customers', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='customers.contact'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='customer_access_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='invitation',
            name='permission_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
