# Generated by Django 5.2.14 on 2026-06-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation_contact_invitation_customer_access_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='employment_type',
            field=models.CharField(choices=[('INTERNAL_STAFF', 'Internal staff'), ('ZZP', 'ZZP (self-employed)'), ('INHUUR', 'Inhuur (hired-in)')], default='INTERNAL_STAFF', max_length=20),
        ),
    ]
