# Generated by Django 5.2.15 on 2026-06-11 09:41

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffprofile_employment_type'),
        ('customers', '0010_add_is_company_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfileProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=accounts.models.profile_property_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility_level', models.CharField(choices=[('PA_SA_ONLY', 'Provider admin / super admin only'), ('PROVIDER_ONLY', 'Any provider-side role'), ('CUSTOMER_VISIBLE', 'Visible to granted customers')], default='PA_SA_ONLY', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('RESIDENCE_PERMIT', 'Residence permit'), ('EU_NATIONAL_ID', 'EU national ID'), ('VCA', 'VCA certificate')], max_length=32)),
                ('permit_number', models.CharField(blank=True, max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=accounts.models.staff_credential_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility_level', models.CharField(choices=[('PA_SA_ONLY', 'Provider admin / super admin only'), ('PROVIDER_ONLY', 'Any provider-side role'), ('CUSTOMER_VISIBLE', 'Visible to granted customers')], default='PA_SA_ONLY', max_length=32)),
                ('document_customer_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialCustomerVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.customer')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_grants', to='accounts.staffcredential')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCustomerVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_grants', to='accounts.customprofileproperty')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'customer'), name='uniq_property_customer_grant')],
            },
        ),
        migrations.AddConstraint(
            model_name='staffcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('credential_type__in', ['RESIDENCE_PERMIT', 'EU_NATIONAL_ID'])), fields=('staff_profile', 'credential_type'), name='uniq_staff_singleton_credential'),
        ),
        migrations.AddConstraint(
            model_name='credentialcustomervisibility',
            constraint=models.UniqueConstraint(fields=('credential', 'customer'), name='uniq_credential_customer_grant'),
        ),
    ]
