# Generated by Django 5.2.15 on 2026-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customprofileproperty_staffcredential_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staffcredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credential_type', 'EU_NATIONAL_ID'), _negated=True), models.Q(('visibility_level', 'PA_SA_ONLY'), ('document_customer_visible', False)), _connector='OR'), name='eu_id_hard_block'),
        ),
    ]
