# Generated by Django 5.2.17 on 2026-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='personnel_number',
            field=models.CharField(blank=True, default='', help_text="The employer's own number for this worker, as it appears on the payroll. Free text: every payroll numbers its people differently.", max_length=32),
        ),
    ]
