# Generated by Django 5.2.14 on 2026-05-14 23:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_buildingstaffvisibility'),
        ('companies', '0001_initial'),
        ('customers', '0004_customer_show_assigned_staff_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('DEEP_CLEANING', 'Deep cleaning'), ('WINDOW_CLEANING', 'Window cleaning'), ('FLOOR_MAINTENANCE', 'Floor maintenance'), ('SANITARY_SERVICE', 'Sanitary service'), ('WASTE_REMOVAL', 'Waste removal'), ('FURNITURE_MOVING', 'Furniture moving'), ('EVENT_CLEANING', 'Event cleaning'), ('EMERGENCY_CLEANING', 'Emergency cleaning'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('category_other_text', models.CharField(blank=True, help_text='Required when category=OTHER. Free-text description of the unlisted category.', max_length=128)),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('PRICING_PROPOSED', 'Pricing proposed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=32)),
                ('customer_visible_note', models.TextField(blank=True)),
                ('pricing_note', models.TextField(blank=True, help_text="Customer-visible note specifically about pricing (e.g. 'price includes weekend surcharge').")),
                ('manager_note', models.TextField(blank=True)),
                ('internal_cost_note', models.TextField(blank=True, help_text='Provider-internal cost / margin / supplier note. Never returned in customer-facing serializers.')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('override_reason', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_proposed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_decided_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_requests', to='buildings.building')),
                ('company', models.ForeignKey(help_text='Provider company that will perform the work.', on_delete=django.db.models.deletion.CASCADE, related_name='extra_work_requests', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_extra_work_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_requests', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_extra_work_requests', to=settings.AUTH_USER_MODEL)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_work_overrides_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraWorkPricingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('HOURS', 'Hours'), ('SQUARE_METERS', 'Square meters'), ('FIXED', 'Fixed'), ('ITEM', 'Item'), ('OTHER', 'Other')], default='FIXED', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_visible_note', models.TextField(blank=True)),
                ('internal_cost_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_line_items', to='extra_work.extraworkrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraWorkStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('PRICING_PROPOSED', 'Pricing proposed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('new_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('PRICING_PROPOSED', 'Pricing proposed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('is_override', models.BooleanField(default=False, help_text='True when a provider operator overrode a customer-side decision. Always paired with a non-empty `note`.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_work_status_changes', to=settings.AUTH_USER_MODEL)),
                ('extra_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='extra_work.extraworkrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='extraworkrequest',
            index=models.Index(fields=['company', 'status'], name='extra_work__company_781fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='extraworkrequest',
            index=models.Index(fields=['building', 'status'], name='extra_work__buildin_2f825a_idx'),
        ),
        migrations.AddIndex(
            model_name='extraworkrequest',
            index=models.Index(fields=['customer', 'status'], name='extra_work__custome_275756_idx'),
        ),
        migrations.AddIndex(
            model_name='extraworkrequest',
            index=models.Index(fields=['deleted_at'], name='extra_work__deleted_aa3947_idx'),
        ),
        migrations.AddIndex(
            model_name='extraworkpricinglineitem',
            index=models.Index(fields=['extra_work'], name='extra_work__extra_w_46935b_idx'),
        ),
        migrations.AddIndex(
            model_name='extraworkstatushistory',
            index=models.Index(fields=['extra_work', 'created_at'], name='extra_work__extra_w_22f118_idx'),
        ),
    ]
