# Generated by Django 5.2.14 on 2026-05-16 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_contact'),
        ('extra_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_type', models.CharField(choices=[('HOURS', 'Hours'), ('SQUARE_METERS', 'Square meters'), ('FIXED', 'Fixed'), ('ITEM', 'Item'), ('OTHER', 'Other')], max_length=20)),
                ('default_unit_price', models.DecimalField(decimal_places=2, help_text='Provider-side reference price for the catalog UI. NOT consumed by the instant-ticket pricing resolver — a customer-specific CustomerServicePrice row is required before a line can skip the proposal phase.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='extra_work.servicecategory')),
            ],
            options={
                'ordering': ['category__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_prices', to='extra_work.service')),
            ],
            options={
                'ordering': ['customer__name', 'service__name', '-valid_from', 'id'],
                'indexes': [models.Index(fields=['service', 'customer', '-valid_from'], name='idx_csp_lookup')],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_service_name_per_category'),
        ),
    ]
