"""
Sprint 28 Batch 6 — add ExtraWorkRequest.routing_decision + the new
ExtraWorkRequestItem model, plus a data backfill that creates exactly
one line item per existing ExtraWorkRequest so the parent / line
relationship is universal from this migration forward.

Backfill rules (mirrored in this migration's `forwards` function):
  * Every existing ExtraWorkRequest gets ONE ExtraWorkRequestItem row.
  * `service=NULL` (legacy requests have no Service catalog FK).
  * `quantity=Decimal("1")`.
  * `unit_type=OTHER` (the legacy single-line request had no notion of
    a unit; OTHER is the safe placeholder).
  * `requested_date = preferred_date or requested_at.date()` — both are
    on the parent already; pick the explicit preferred date when set,
    fall back to the request's own creation date otherwise.
  * `customer_note=""` — the legacy `description` lives on the parent
    and stays there. Replicating it into the line would create two
    sources of truth for the same fact; leaving it blank is safer.
  * `routing_decision="PROPOSAL"` on every backfilled request. The
    instant-ticket flow is gated on a customer-specific contract
    price (per master plan §5 rule #9); legacy requests have no
    line-level service FK so the resolver cannot return a contract
    row → PROPOSAL is the correct conservative default.

Reverse migration is a no-op: data migrations that create new rows
are not cleanly reversible without risking dropping rows an operator
added post-migration. The schema operations themselves (field add,
model create) are reversible via the standard Django machinery, so
`manage.py migrate extra_work 0002` still works — it just won't try
to delete the line-item rows.
"""
# Generated by Django 5.2.14 on 2026-05-16 18:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# Hard-coded literals: data migrations do not import live models /
# enums (Django convention is `apps.get_model` only).
_UNIT_TYPE_OTHER = "OTHER"
_ROUTING_PROPOSAL = "PROPOSAL"


def backfill_line_items_and_routing(apps, schema_editor):
    ExtraWorkRequest = apps.get_model("extra_work", "ExtraWorkRequest")
    ExtraWorkRequestItem = apps.get_model(
        "extra_work", "ExtraWorkRequestItem"
    )

    rows_to_create = []
    requests_to_update = []
    for ew in ExtraWorkRequest.objects.all().iterator():
        # Defensive: skip if a parallel path already created a line item
        # for this request (shouldn't happen on a clean migrate, but the
        # check keeps the backfill idempotent under reapply).
        if ExtraWorkRequestItem.objects.filter(
            extra_work_request=ew
        ).exists():
            continue

        requested_date = ew.preferred_date or ew.requested_at.date()
        rows_to_create.append(
            ExtraWorkRequestItem(
                extra_work_request=ew,
                service=None,
                quantity=Decimal("1"),
                unit_type=_UNIT_TYPE_OTHER,
                requested_date=requested_date,
                customer_note="",
            )
        )

        # Force PROPOSAL on every backfilled request. The AddField
        # default already fills the column server-side with PROPOSAL,
        # so this is belt-and-braces — also survives reapply if an
        # operator manually flipped a row to INSTANT before realising
        # the line still has service=NULL.
        if ew.routing_decision != _ROUTING_PROPOSAL:
            ew.routing_decision = _ROUTING_PROPOSAL
            requests_to_update.append(ew)

    if rows_to_create:
        ExtraWorkRequestItem.objects.bulk_create(rows_to_create)
    if requests_to_update:
        ExtraWorkRequest.objects.bulk_update(
            requests_to_update, ["routing_decision"]
        )


def reverse_noop(apps, schema_editor):
    # Intentional no-op. See module docstring: deleting line items on
    # rollback is too risky once operators have started creating real
    # cart lines through the Batch 6 serializer.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0002_service_catalog_and_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='routing_decision',
            field=models.CharField(choices=[('INSTANT', 'Instant ticket'), ('PROPOSAL', 'Proposal')], default='PROPOSAL', max_length=10),
        ),
        migrations.CreateModel(
            name='ExtraWorkRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_type', models.CharField(choices=[('HOURS', 'Hours'), ('SQUARE_METERS', 'Square meters'), ('FIXED', 'Fixed'), ('ITEM', 'Item'), ('OTHER', 'Other')], help_text="Denormalised from Service.unit_type at create time so a later catalog edit cannot rewrite the historical cart line's pricing semantics.", max_length=20)),
                ('requested_date', models.DateField()),
                ('customer_note', models.TextField(blank=True, default='', help_text='Per-line free-text note from the customer. Distinct from the request-level `description` which describes the cart as a whole.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='extra_work.extraworkrequest')),
                ('service', models.ForeignKey(blank=True, help_text='Catalog row for this cart line. NULL on rows backfilled from legacy single-line ExtraWorkRequests; new submissions enforce non-null + Service.is_active.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='extra_work.service')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['extra_work_request'], name='extra_work__extra_w_03c55f_idx')],
            },
        ),
        migrations.RunPython(
            backfill_line_items_and_routing,
            reverse_noop,
        ),
    ]
