# Generated by Django 5.2.14 on 2026-05-16 21:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0003_request_items_and_routing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer_decided_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('extra_work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='extra_work.extraworkrequest')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_work_proposal_overrides_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Free-text label for ad-hoc lines. Required when `service` is NULL.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_type', models.CharField(choices=[('HOURS', 'Hours'), ('SQUARE_METERS', 'Square meters'), ('FIXED', 'Fixed'), ('ITEM', 'Item'), ('OTHER', 'Other')], help_text='Denormalised at create time so a later catalog edit to the linked Service does not rewrite history.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('customer_explanation', models.TextField(blank=True, default='', help_text='Customer-visible per-line explanation. Surfaced on the customer-facing proposal serializer and on the spawned Ticket description (Batch 8 spec §6).')),
                ('internal_note', models.TextField(blank=True, default='', help_text='Provider-only per-line note. NEVER serialized for CUSTOMER_USER; never propagated into spawned Ticket descriptions (Batch 8 spec §6).')),
                ('is_approved_for_spawn', models.BooleanField(default=True, help_text='Per-line approval slot. When False the ticket-spawn helper skips this line on customer approval. Forward-compat for a future per-line approval UX.')),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='extra_work.proposal')),
                ('service', models.ForeignKey(blank=True, help_text='NULL when this is an ad-hoc line (no catalog link).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_lines', to='extra_work.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('is_override', models.BooleanField(default=False, help_text='True when a provider operator drove a customer-decision transition. Always paired with a non-empty override_reason.')),
                ('override_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='extra_work.proposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('CUSTOMER_VIEWED', 'Customer viewed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('ADMIN_OVERRIDDEN', 'Admin overridden'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('customer_visible', models.BooleanField(default=True, help_text='Set at emission time. The customer-facing timeline endpoint filters `customer_visible=True`.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Provider-side context (e.g. {'override_reason': ...}). Stripped from the customer-facing serializer entirely.")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='extra_work.proposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SENT'])), fields=('extra_work_request',), name='uniq_proposal_open_per_request'),
        ),
        migrations.AddIndex(
            model_name='proposalline',
            index=models.Index(fields=['proposal'], name='extra_work__proposa_7897bb_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalstatushistory',
            index=models.Index(fields=['proposal', 'created_at'], name='extra_work__proposa_3f46f4_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaltimelineevent',
            index=models.Index(fields=['proposal', 'created_at'], name='extra_work__proposa_ce81d0_idx'),
        ),
    ]
