# Generated by Django 5.2.13 on 2026-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0004_proposal_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraworkrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('PRICING_PROPOSED', 'Pricing proposed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=32),
        ),
        migrations.AlterField(
            model_name='extraworkstatushistory',
            name='new_status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('PRICING_PROPOSED', 'Pricing proposed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='extraworkstatushistory',
            name='old_status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('PRICING_PROPOSED', 'Pricing proposed'), ('CUSTOMER_APPROVED', 'Customer approved'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CUSTOMER_REJECTED', 'Customer rejected'), ('CANCELLED', 'Cancelled')], max_length=32),
        ),
    ]
