"""
Sprint 2A — explicit Extra Work request intent, ad-hoc cart-line
support, and per-line price-source classification + agreed-price
snapshot columns on ExtraWorkRequestItem.

Schema additions:
  * `ExtraWorkRequest.request_intent` (nullable enum) —
    DIRECT_AGREED_PRICE_ORDER / AUTO_START_AFTER_PRICING /
    REQUEST_QUOTE. Separate from lifecycle status.
  * `ExtraWorkRequestItem.custom_description` (CharField, blank) —
    free-text label for ad-hoc cart lines (service IS NULL).
  * `ExtraWorkRequestItem.line_price_source` (nullable enum) —
    AGREED_CUSTOMER_PRICE / NEEDS_PROVIDER_PRICING / AD_HOC.
  * `ExtraWorkRequestItem.snapshot_unit_price`,
    `snapshot_vat_pct`, `snapshot_service_name`,
    `snapshot_service_category_name`,
    `snapshot_customer_service_price` — agreed-price snapshot
    surface so a later CustomerServicePrice / Service edit cannot
    rewrite the historical line.

Backfill rules (mirrored in `forwards` below):
  * `ExtraWorkRequest.request_intent`:
      - `routing_decision == "INSTANT"`  ⇒ DIRECT_AGREED_PRICE_ORDER
      - `routing_decision == "PROPOSAL"` ⇒ REQUEST_QUOTE
        (REQUEST_QUOTE is the safest historical default — it never
        bypasses the customer-approval step; AUTO_START_AFTER_PRICING
        would mis-classify history as having pre-authorised auto-
        start which it did not.)
  * `ExtraWorkRequestItem.line_price_source`:
      - `service IS NULL` AND `custom_description != ""` ⇒ AD_HOC
        (real customer-entered free-text line — but the
        `custom_description` column is only added in THIS same
        migration with default `""`, so this branch only fires for
        forward-compat reapply cases where an operator manually
        flipped a column value between the field-add and the
        backfill).
      - `service IS NULL` AND `custom_description == ""` ⇒
        NEEDS_PROVIDER_PRICING. **Legacy single-line rows from
        migration 0003 land here.** They are synthetic backfill
        rows, NOT customer-entered ad-hoc lines, so marking them
        AD_HOC would mis-classify history as customer-typed
        free-text work that was never typed.
      - else (service set) parent.routing_decision == "INSTANT" ⇒
        AGREED_CUSTOMER_PRICE.
      - else NEEDS_PROVIDER_PRICING.
  * `snapshot_*` columns stay NULL on backfilled rows — we have no
    historical contract row to capture and we explicitly do NOT
    call `resolve_price()` from a migration (`apps.get_model` does
    not expose live-code helpers; running today's resolver against
    historical dates would be wrong anyway).

Reverse migration is a no-op for the data step (mirrors migration
0003): re-running the backfill on rollback risks dropping operator-
set values. Schema reversal via `manage.py migrate extra_work 0005`
still works for the AddField operations themselves.
"""
# Generated by Django 5.2.14 on 2026-05-30 20:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# Hard-coded literals — data migrations cannot import live enums.
_INTENT_DIRECT = "DIRECT_AGREED_PRICE_ORDER"
_INTENT_REQUEST_QUOTE = "REQUEST_QUOTE"
_SOURCE_AGREED = "AGREED_CUSTOMER_PRICE"
_SOURCE_NEEDS = "NEEDS_PROVIDER_PRICING"
_SOURCE_AD_HOC = "AD_HOC"
_ROUTING_INSTANT = "INSTANT"


def backfill_intent_and_line_source(apps, schema_editor):
    ExtraWorkRequest = apps.get_model("extra_work", "ExtraWorkRequest")
    ExtraWorkRequestItem = apps.get_model(
        "extra_work", "ExtraWorkRequestItem"
    )

    requests_to_update = []
    for ew in ExtraWorkRequest.objects.all().iterator():
        if ew.request_intent:
            continue
        ew.request_intent = (
            _INTENT_DIRECT
            if ew.routing_decision == _ROUTING_INSTANT
            else _INTENT_REQUEST_QUOTE
        )
        requests_to_update.append(ew)
    if requests_to_update:
        ExtraWorkRequest.objects.bulk_update(
            requests_to_update, ["request_intent"]
        )

    items_to_update = []
    for item in (
        ExtraWorkRequestItem.objects.select_related("extra_work_request")
        .all()
        .iterator()
    ):
        if item.line_price_source:
            continue
        # AD_HOC requires BOTH a NULL service AND a non-empty
        # custom_description. Legacy migration-0003 backfill rows
        # have service IS NULL but custom_description == "" — those
        # are synthetic single-line placeholders, not customer-
        # typed free-text lines, and must NOT be labelled AD_HOC.
        if item.service_id is None:
            if (item.custom_description or "").strip():
                item.line_price_source = _SOURCE_AD_HOC
            else:
                item.line_price_source = _SOURCE_NEEDS
        else:
            parent_routing = item.extra_work_request.routing_decision
            item.line_price_source = (
                _SOURCE_AGREED
                if parent_routing == _ROUTING_INSTANT
                else _SOURCE_NEEDS
            )
        items_to_update.append(item)
    if items_to_update:
        ExtraWorkRequestItem.objects.bulk_update(
            items_to_update, ["line_price_source"]
        )


def reverse_noop(apps, schema_editor):
    # Intentional no-op. See module docstring.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0005_sprint29_batch29_8_operational_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='request_intent',
            field=models.CharField(blank=True, choices=[('DIRECT_AGREED_PRICE_ORDER', 'Direct agreed-price order'), ('AUTO_START_AFTER_PRICING', 'Auto-start after pricing'), ('REQUEST_QUOTE', 'Request a quote')], default=None, help_text='Sprint 2A — DIRECT_AGREED_PRICE_ORDER / AUTO_START_AFTER_PRICING / REQUEST_QUOTE. Separate from lifecycle status.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='custom_description',
            field=models.CharField(blank=True, default='', help_text='Sprint 2A — free-text label for ad-hoc cart lines. Required when `service` is NULL; must be empty when `service` is set.', max_length=255),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='line_price_source',
            field=models.CharField(blank=True, choices=[('AGREED_CUSTOMER_PRICE', 'Agreed customer price'), ('NEEDS_PROVIDER_PRICING', 'Needs provider pricing'), ('AD_HOC', 'Ad-hoc / free-text')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='snapshot_customer_service_price',
            field=models.ForeignKey(blank=True, default=None, help_text='Sprint 2A — the CustomerServicePrice row resolved at create time. SET_NULL so deleting the contract row does not delete operational history; the snapshot_* columns are the durable audit trail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshotted_line_items', to='extra_work.customerserviceprice'),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='snapshot_service_category_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='snapshot_service_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='snapshot_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='snapshot_vat_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(
            backfill_intent_and_line_source,
            reverse_noop,
        ),
    ]
