# Generated by Django 5.2.14 on 2026-05-31 00:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_sprint3b_provider_admin_catalog_policies'),
        ('extra_work', '0006_sprint2a_request_intent_and_line_snapshots'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='uniq_service_name_per_category',
        ),
        migrations.AddField(
            model_name='service',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Sprint 3B — provider company that owns this catalog row. Required on every API-created Service; pre-3B legacy rows are backfilled via migration 0008.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Provider-side reference price for the catalog UI. NOT consumed by the instant-ticket pricing resolver — a customer-specific CustomerServicePrice row is required before a line can skip the proposal phase. Sprint 3B stripped from CUSTOMER_USER / STAFF API reads.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('company', 'category', 'name'), name='uniq_service_name_per_company_category'),
        ),
    ]
