# Generated by Django 5.2.14 on 2026-05-31 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0009_sprint3b_service_company_not_null'),
        ('tickets', '0013_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='source_ticket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_extra_work_requests', to='tickets.ticket'),
        ),
    ]
