# Generated by Django 5.2.14 on 2026-06-07 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0011_sprint8b_actual_hours_and_final_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWorkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('PUBLIC_REPLY', 'Public Reply'), ('INTERNAL_NOTE', 'Internal Note (provider-internal)'), ('CUSTOMER_INTERNAL', 'Customer Internal Note')], default='PUBLIC_REPLY', max_length=32)),
                ('visibility_mode', models.CharField(choices=[('NORMAL', 'Normal'), ('RESTRICTED', 'Restricted')], db_index=True, default='NORMAL', max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_work_messages', to=settings.AUTH_USER_MODEL)),
                ('directed_to', models.ManyToManyField(blank=True, related_name='directed_extra_work_messages', to=settings.AUTH_USER_MODEL)),
                ('extra_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='extra_work.extraworkrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['extra_work', 'created_at'], name='extra_work__extra_w_4cb349_idx')],
            },
        ),
    ]
