# Generated by Django 5.2.15 on 2026-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0012_extraworkmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
