# Generated by Django 5.2.15 on 2026-06-21 20:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_add_is_company_admin'),
        ('extra_work', '0013_m4_billing_month_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCustomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('HOURS', 'Hours'), ('SQUARE_METERS', 'Square meters'), ('FIXED', 'Fixed'), ('ITEM', 'Item'), ('OTHER', 'Other')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='customers.customer')),
            ],
            options={
                'ordering': ['customer__name', 'custom_name', '-valid_from', 'id'],
                'indexes': [models.Index(fields=['customer', '-valid_from'], name='idx_ccp_lookup')],
            },
        ),
    ]
