# Generated by Django 5.2.16 on 2026-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0014_customercustomprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercustomprice',
            name='custom_unit_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
