# Generated by Django 5.2.16 on 2026-07-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0016_proposalline_custom_unit_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_unit_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
