# Generated by Django 5.2.16 on 2026-07-27 14:52

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_logo'),
        ('extra_work', '0017_service_custom_unit_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Operator-facing display label, e.g. "m³", "strekkende meter".', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Archiving (is_active=False) removes a unit from the everyday picker without breaking rows that already reference it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company that owns this unit. PROTECT mirrors Service.company: a Company cannot be hard-deleted while it still has managed units.', on_delete=django.db.models.deletion.PROTECT, related_name='managed_units', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'label', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customercustomprice',
            name='managed_unit',
            field=models.ForeignKey(blank=True, help_text='Sprint 123 — optional managed-unit catalog link, only meaningful when unit_type=OTHER. Must belong to the same company as customer.company (enforced in the serializer).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_prices', to='extra_work.managedunit'),
        ),
        migrations.AddField(
            model_name='service',
            name='managed_unit',
            field=models.ForeignKey(blank=True, help_text='Sprint 123 — optional managed-unit catalog link, only meaningful when unit_type=OTHER. PROTECT: archiving a unit is always safe; deleting one still in use is not.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='extra_work.managedunit'),
        ),
        migrations.AddConstraint(
            model_name='managedunit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('label')), models.F('company'), name='uniq_managed_unit_label_per_company_ci'),
        ),
    ]
