# Generated by Django 5.2.16 on 2026-07-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0019_sprint123_managed_unit_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercustomprice',
            name='managed_unit',
            field=models.ForeignKey(blank=True, help_text='Sprint 123 — optional managed-unit catalog link, only meaningful when unit_type=OTHER. Must belong to the same company as customer.company (enforced in the view — see views_catalog.py::_enforce_same_company_managed_unit).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_prices', to='extra_work.managedunit'),
        ),
    ]
