# Generated by Django 5.2.16 on 2026-07-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_department_worktype'),
        ('extra_work', '0020_alter_customercustomprice_managed_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_requests', to='customers.department'),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_requests', to='customers.worktype'),
        ),
    ]
