# Generated by Django 5.2.16 on 2026-08-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0021_extraworkrequest_department_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequestitem',
            name='snapshot_customer_custom_price',
            field=models.ForeignKey(blank=True, default=None, help_text='Sprint 137 item 6 — the CustomerCustomPrice row this ad-hoc line was ordered from. SET_NULL: the snapshot_* columns are the durable record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshotted_line_items', to='extra_work.customercustomprice'),
        ),
    ]
