# Generated by Django 5.2.16 on 2026-08-05 14:51

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_invoice_granularity_default'),
        ('extra_work', '0025_sprint142_category_company_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPriceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text="Archiving a folder hides it from the Extra Work form's picker without touching the price rows inside it.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_price_folders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_folders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer price folder',
                'verbose_name_plural': 'customer price folders',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customercustomprice',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_prices', to='extra_work.customerpricefolder'),
        ),
        migrations.AddField(
            model_name='customerserviceprice',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='extra_work.customerpricefolder'),
        ),
        migrations.AddConstraint(
            model_name='customerpricefolder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('customer'), name='uniq_price_folder_name_per_customer_ci'),
        ),
    ]
