# Generated by Django 5.2.16 on 2026-08-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0026_sprint143_customer_price_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='price_folder',
            field=models.ForeignKey(blank=True, help_text="Sprint 144 — the customer's own price folder this request is filed under. Mutually exclusive with `service_category`.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_requests', to='extra_work.customerpricefolder'),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Sprint 144 — the company catalog category this request is filed under. Mutually exclusive with `price_folder`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_requests', to='extra_work.servicecategory'),
        ),
    ]
