# Generated by Django 5.2.16 on 2026-08-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0027_sprint144_request_category_and_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('WORKER', 'Worker'), ('MANAGER', 'Manager')], default='WORKER', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_work_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('extra_work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='extra_work.extraworkrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'id'],
                'indexes': [models.Index(fields=['extra_work_request', 'role'], name='extra_work__extra_w_d1f3c7_idx'), models.Index(fields=['user', 'role'], name='extra_work__user_id_e357c9_idx')],
                'unique_together': {('extra_work_request', 'user', 'role')},
            },
        ),
    ]
