# Generated by Django 5.2.17 on 2026-08-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0029_sprint161_drop_ineligible_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='deadline',
            field=models.DateField(blank=True, help_text='The date by which this must be finished. A record past it and not finished is marked overdue.', null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='planned_end_date',
            field=models.DateField(blank=True, help_text='Last planned day. With `preferred_date` this is the planned WINDOW; NULL means the job is planned for the one day rather than for a span.', null=True),
        ),
    ]
