# Generated by Django 5.2.17 on 2026-08-19 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0032_sprint182_billed_to_nullable_and_provider_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='budget_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='W2-D — planned total hours for the job. A planning and control number ONLY: it reaches no price anywhere. NULL means unbudgeted, which is not the same as 0.00.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='completion_notes_required',
            field=models.BooleanField(default=False, help_text='W2-D — a completion note must be written before this work may be completed. Stored here; enforced in the completion transition (wave 3).'),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='file_upload_required',
            field=models.BooleanField(default=False, help_text='W2-D — a file must be attached before this work may be completed. Stored here; enforced in the completion transition (wave 3).'),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='provider_planned_end_date',
            field=models.DateField(blank=True, default=None, help_text="W2-D — the day the PROVIDER expects to finish. With `provider_planned_date` this is the COMMITTED window, held separately from the customer's requested window (`preferred_date` -> `planned_end_date`). NULL means the provider has committed to a start but not to an end.", null=True),
        ),
        migrations.CreateModel(
            name='ExtraWorkPlannedHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Planned hours for this person on this job. A planning number: it reaches no price anywhere.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('extra_work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_hours', to='extra_work.extraworkrequest')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_work_planned_hours_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_planned_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'extra work planned hours',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['extra_work_request'], name='extra_work__extra_w_01ce9b_idx')],
                'unique_together': {('extra_work_request', 'user')},
            },
        ),
    ]
