# Generated by Django 5.2.17 on 2026-08-20 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_sprint185_building_cost_share'),
        ('companies', '0005_company_logo'),
        ('customers', '0019_sprint185_customer_address_lifecycle_contact_invoices'),
        ('extra_work', '0033_w2d_planning_layer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='condition',
            field=models.CharField(blank=True, choices=[('AT_HANDOVER', 'At handover'), ('BEFORE_HANDOVER', 'Before handover'), ('AFTER_HANDOVER', 'After handover')], default=None, help_text='When this work happens relative to the handover. A REAL COLUMN. The reference system keeps this value only as five characters inside the title and every reader recovers it with a regex, which is why two title formats now coexist there and the parser only understands one of them (A7 §1.3). Never parse this out of a title.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='group_sequence',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, default=None, help_text='Time of day for this occurrence. Held as a real column rather than inside the title string.', null=True),
        ),
        migrations.CreateModel(
            name='ExtraWorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_work_groups', to='buildings.building')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_work_groups', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extra_work_groups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_work_groups', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='group',
            field=models.ForeignKey(blank=True, default=None, help_text="The multi-date batch this work was created in, or NULL for an ordinary single work. A group is a creation and editing convenience only: this work's status, price, hours and invoice are entirely its own.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='extra_work.extraworkgroup'),
        ),
        migrations.AddIndex(
            model_name='extraworkgroup',
            index=models.Index(fields=['company', 'customer'], name='extra_work__company_0ae7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='extraworkgroup',
            index=models.Index(fields=['building'], name='extra_work__buildin_dd84da_idx'),
        ),
    ]
