# Generated by Django 5.2.17 on 2026-08-20 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0034_w5b_multi_date_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraworkplannedhours',
            options={'ordering': ['date', 'id'], 'verbose_name_plural': 'extra work planned hours'},
        ),
        migrations.AlterUniqueTogether(
            name='extraworkplannedhours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extraworkplannedhours',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=None, help_text="The day these hours are planned for, or NULL for 'planned, day not decided'. A planning number: it reaches no price anywhere.", null=True),
        ),
        migrations.AddIndex(
            model_name='extraworkplannedhours',
            index=models.Index(fields=['extra_work_request', 'date'], name='extra_work__extra_w_9311c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='extraworkplannedhours',
            constraint=models.UniqueConstraint(fields=('extra_work_request', 'user', 'date'), name='uniq_ew_planned_hours_person_day'),
        ),
        migrations.AddConstraint(
            model_name='extraworkplannedhours',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', True)), fields=('extra_work_request', 'user'), name='uniq_ew_planned_hours_person_undated'),
        ),
    ]
