# Generated by Django 5.2.17 on 2026-08-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0035_w6h_planned_hours_day'),
        ('timesheets', '0009_timeentry_source_id_timeentry_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraworkplannedhours',
            options={'ordering': ['date', 'hour_type_id', 'id'], 'verbose_name_plural': 'extra work planned hours'},
        ),
        migrations.RemoveConstraint(
            model_name='extraworkplannedhours',
            name='uniq_ew_planned_hours_person_day',
        ),
        migrations.RemoveConstraint(
            model_name='extraworkplannedhours',
            name='uniq_ew_planned_hours_person_undated',
        ),
        migrations.AddField(
            model_name='extraworkplannedhours',
            name='hour_type',
            field=models.ForeignKey(blank=True, default=None, help_text='Which kind of hour is planned, or NULL for ordinary hours. The same per-company catalog the timesheets actuals use. A planning number: it reaches no price anywhere.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_work_planned_hours', to='timesheets.hourtype'),
        ),
        migrations.AddConstraint(
            model_name='extraworkplannedhours',
            constraint=models.UniqueConstraint(fields=('extra_work_request', 'user', 'date', 'hour_type'), name='uniq_ew_planned_hours_person_day_type', nulls_distinct=False),
        ),
    ]
