# Generated by Django 5.2.17 on 2026-08-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0036_w7_planned_hours_hour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraworkrequest',
            name='customer_requires_note',
            field=models.BooleanField(default=False, help_text="W13 — the CUSTOMER asked for a written note when they raised this request. Independent of the provider's `completion_notes_required`; the completion gate requires a note if either is set."),
        ),
        migrations.AddField(
            model_name='extraworkrequest',
            name='customer_requires_photo',
            field=models.BooleanField(default=False, help_text="W13 — the CUSTOMER asked for photo proof when they raised this request. Independent of the provider's `file_upload_required`; the completion gate requires evidence if either is set."),
        ),
    ]
