# Generated by Django 5.2.17 on 2026-08-20 02:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Euros per hour of work, applied to WEIGHTED hours so an overtime hour costs what its multiplier says. Must be at least 0.01: zero is a legal price but not a legal wage.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valid_from', models.DateField(help_text='First day this rate is in force. Open-ended — it stays in force until a row with a later valid_from supersedes it. Hours dated BEFORE this day keep resolving the previous row, which is what stops a raise re-pricing history.')),
                ('note', models.CharField(blank=True, default='', help_text="Why the rate changed, in the operator's own words. Free text and optional; it is read by people, never parsed.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company this rate applies within — the tenant anchor, the same shape TimeEntry.company and ContractHours.company use. A person who works for two providers has two rates and neither can read the other.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_hourly_rates', to='companies.company')),
                ('created_by', models.ForeignKey(help_text='Who recorded this rate. PROTECT: an author is never erased.', on_delete=django.db.models.deletion.PROTECT, related_name='created_employee_hourly_rates', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The provider-side employee this rate is for. Never a customer-side user, never a SUPER_ADMIN — a platform admin is not a provider employee and cannot have hours filed against them (timesheets.scope.PROVIDER_EMPLOYEE_ROLES).', on_delete=django.db.models.deletion.PROTECT, related_name='hourly_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
                'indexes': [models.Index(fields=['company', 'employee', 'valid_from'], name='rep_emp_rate_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'valid_from'), name='uniq_employee_hourly_rate_per_start_date')],
            },
        ),
    ]
