# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TICKET_CREATED", "Ticket created"),
                    ("TICKET_STATUS_CHANGED", "Ticket status changed"),
                    ("TICKET_ASSIGNED", "Ticket assigned"),
                    ("PASSWORD_RESET", "Password reset"),
                ],
                max_length=64,
            ),
        ),
    ]
