# Generated by Django 5.2.13 on 2026-05-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog_password_reset_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('PASSWORD_RESET', 'Password reset')], max_length=64),
        ),
    ]
