# Generated by Django 5.2.13 on 2026-05-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent')], max_length=64)),
                ('muted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type'], name='notificatio_user_id_a544c1_idx')],
                'unique_together': {('user', 'event_type')},
            },
        ),
    ]
