# Generated by Django 5.2.14 on 2026-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent')], max_length=64),
        ),
    ]
