# Generated by Django 5.2.14 on 2026-06-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TICKET_MESSAGE', 'Ticket message'), ('EXTRA_WORK_REQUESTED', 'Extra work requested'), ('EXTRA_WORK_PROPOSAL_SENT', 'Extra work proposal sent'), ('EXTRA_WORK_DECISION', 'Extra work decision')], max_length=32),
        ),
    ]
