# Generated by Django 5.2.14 on 2026-06-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TICKET_MESSAGE', 'Ticket message'), ('EXTRA_WORK_REQUESTED', 'Extra work requested'), ('EXTRA_WORK_PROPOSAL_SENT', 'Extra work proposal sent'), ('EXTRA_WORK_DECISION', 'Extra work decision'), ('EXTRA_WORK_MESSAGE', 'Extra work message'), ('EXTRA_WORK_PUBLISHED', 'Extra work published')], max_length=32),
        ),
    ]
