# Generated by Django 5.2.16 on 2026-07-17 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0015_rf2_custom_unit_label'),
        ('notifications', '0010_alter_notification_event_type'),
        ('tickets', '0022_alter_ticketmessage_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_read_cursors', to='extra_work.extraworkrequest')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_read_cursors', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ticket'], name='notificatio_user_id_1296a0_idx'), models.Index(fields=['user', 'extra_work'], name='notificatio_user_id_bc5e97_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('extra_work__isnull', True), ('ticket__isnull', False)), models.Q(('extra_work__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='mrc_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('ticket__isnull', False)), fields=('user', 'ticket'), name='mrc_unique_user_ticket'), models.UniqueConstraint(condition=models.Q(('extra_work__isnull', False)), fields=('user', 'extra_work'), name='mrc_unique_user_extra_work')],
            },
        ),
    ]
