# Generated by Django 5.2.16 on 2026-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_messagereadcursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('TICKET_MESSAGE', 'Ticket message (in-app feed)'), ('EXTRA_WORK_MESSAGE', 'Extra work message (in-app feed)')], max_length=64),
        ),
    ]
