# Generated by Django 5.2.16 on 2026-07-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_superadmincompanysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmincompanysubscription',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
