"""Sprint W1-B §2.7 — the time-driven warning family.

Additive only, and the three operations are not equally interesting:

  * AddField `NotificationLog.extra_work` — a NULLABLE FK, so every
    existing row is valid without a backfill. It is the cooldown key for
    warnings about an Extra Work that has not spawned an operational
    ticket yet and therefore has no `ticket` to key on.
  * the two AlterField operations are CHOICES-ONLY changes on existing
    CharFields. Django emits them for the three new
    `NotificationEventType` members; they touch no column type, no
    constraint and no data.
"""

# Generated by Django 5.2.17 on 2026-08-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0032_sprint182_billed_to_nullable_and_provider_date'),
        ('notifications', '0016_sprint185_invoice_sent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='extra_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='extra_work.extraworkrequest'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_MESSAGE', 'Ticket message (in-app feed)'), ('EXTRA_WORK_MESSAGE', 'Extra work message (in-app feed)')], max_length=64),
        ),
    ]
