# Generated by Django 5.2.16 on 2026-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TICKET_MESSAGE', 'Ticket message'), ('EXTRA_WORK_REQUESTED', 'Extra work requested'), ('EXTRA_WORK_PROPOSAL_SENT', 'Extra work proposal sent'), ('EXTRA_WORK_DECISION', 'Extra work decision'), ('EXTRA_WORK_MESSAGE', 'Extra work message'), ('EXTRA_WORK_PUBLISHED', 'Extra work published'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned'), ('TICKET_MESSAGE', 'Ticket message (in-app feed)'), ('EXTRA_WORK_MESSAGE', 'Extra work message (in-app feed)')], max_length=64),
        ),
    ]
