# Generated by Django 5.2.16 on 2026-08-26 15:00

from django.db import migrations, models


#: W-LATE addendum 2 — the rows that rendered as a WARNING before the
#: ladder existed (the three SLA sweeps) plus the deadline reminder,
#: which is the same kind of thing. Lifted from the new column's INFO
#: default to L1 so a row that read as a warning yesterday reads as the
#: same warning today for the same reason — the client no longer keeps a
#: type list to decide the tone. Spelled out here rather than imported
#: from the model module, so this migration keeps meaning what it meant
#: whatever the enum grows into later.
L1_BACKFILL_TYPES = [
    "SLA_APPROVAL_CUTOFF_DUE",
    "SLA_MANAGER_REVIEW_OVERDUE",
    "SLA_WORK_NOT_STARTED",
    "TICKET_DEADLINE_APPROACHING",
]


def backfill_severity(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(event_type__in=L1_BACKFILL_TYPES).update(
        severity="L1"
    )


def unbackfill_severity(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(event_type__in=L1_BACKFILL_TYPES).update(
        severity="INFO"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_w_n1_deadline_and_part_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('L1', 'Level 1 — plan passed'), ('L2', 'Level 2 — deadline passed'), ('L3', 'Level 3 — quarantine')], default='INFO', max_length=4),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TICKET_MESSAGE', 'Ticket message'), ('EXTRA_WORK_REQUESTED', 'Extra work requested'), ('EXTRA_WORK_PROPOSAL_SENT', 'Extra work proposal sent'), ('EXTRA_WORK_DECISION', 'Extra work decision'), ('EXTRA_WORK_MESSAGE', 'Extra work message'), ('EXTRA_WORK_PUBLISHED', 'Extra work published'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned'), ('TICKET_LATE_L2_MANAGERS', 'Deadline passed: assigned managers notified'), ('TICKET_LATE_L2_ESCALATED', 'Deadline still passed: managers and admins notified'), ('TICKET_LATE_L3_QUARANTINE', 'Quarantine: provider admins notified')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned'), ('TICKET_LATE_L2_MANAGERS', 'Deadline passed: assigned managers notified'), ('TICKET_LATE_L2_ESCALATED', 'Deadline still passed: managers and admins notified'), ('TICKET_LATE_L3_QUARANTINE', 'Quarantine: provider admins notified')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned'), ('TICKET_LATE_L2_MANAGERS', 'Deadline passed: assigned managers notified'), ('TICKET_LATE_L2_ESCALATED', 'Deadline still passed: managers and admins notified'), ('TICKET_LATE_L3_QUARANTINE', 'Quarantine: provider admins notified'), ('TICKET_MESSAGE', 'Ticket message (in-app feed)'), ('EXTRA_WORK_MESSAGE', 'Extra work message (in-app feed)')], max_length=64),
        ),
            migrations.RunPython(backfill_severity, unbackfill_severity),
    ]
