# Generated by Django 5.2.16 on 2026-08-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_w_late_severity_and_escalation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('SLA_WEEKLY_SUMMARY', 'Weekly list of warnings sent'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned'), ('TICKET_LATE_L2_MANAGERS', 'Deadline passed: assigned managers notified'), ('TICKET_LATE_L2_ESCALATED', 'Deadline still passed: managers and admins notified'), ('TICKET_LATE_L3_QUARANTINE', 'Quarantine: provider admins notified')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_STATUS_CHANGED', 'Ticket status changed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_SLOT_UNABLE', 'Staff slot unable to complete'), ('PASSWORD_RESET', 'Password reset'), ('INVITATION_SENT', 'Invitation sent'), ('INVOICE_RUN_COMPLETED', 'Invoice run completed'), ('INVOICE_SENT', 'Invoice sent'), ('SLA_APPROVAL_CUTOFF_DUE', 'Customer approval due before billing cutoff'), ('SLA_MANAGER_REVIEW_OVERDUE', 'Manager review overdue'), ('SLA_WORK_NOT_STARTED', 'Planned work has not started'), ('SLA_WEEKLY_SUMMARY', 'Weekly list of warnings sent'), ('TICKET_DEADLINE_APPROACHING', 'Ticket deadline approaching'), ('TICKET_PART_ASSIGNED', 'Ticket part assigned'), ('TICKET_LATE_L2_MANAGERS', 'Deadline passed: assigned managers notified'), ('TICKET_LATE_L2_ESCALATED', 'Deadline still passed: managers and admins notified'), ('TICKET_LATE_L3_QUARANTINE', 'Quarantine: provider admins notified'), ('TICKET_MESSAGE', 'Ticket message (in-app feed)'), ('EXTRA_WORK_MESSAGE', 'Extra work message (in-app feed)')], max_length=64),
        ),
    ]
