# Generated by Django 5.2.16 on 2026-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_p5_sla_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='template_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='template_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
