# Generated by Django 5.2.16 on 2026-08-10 16:10
#
# Sprint 160 — the contracts module's initial schema. Purely ADDITIVE:
# six new tables, no existing table altered, no data migration, nothing
# to backfill. Every FK out of this app (companies, customers,
# buildings, auth user) points OUTWARD only — no existing model gains a
# column, so nothing outside `contracts` changes shape.
#
# Two constraints are created WITH their tables rather than retrofitted:
#
#   * `uniq_contract_type_name_per_company_ci` — the same
#     case/whitespace-insensitive per-company uniqueness `HourType` has.
#     `ServiceCategory` and `ManagedUnit` reached it through a
#     nullable-column / backfill / NOT NULL sequence because they were
#     retrofitting a company FK onto existing rows; there is nothing
#     here to retrofit.
#   * `contract_lifecycle_is_storable` — the CHECK that keeps EXPIRED
#     out of the stored status. It is what makes "the status cannot
#     contradict the dates" a schema fact rather than a convention: a
#     row whose stored lifecycle claimed EXPIRED is rejected by
#     Postgres, so `Contract.status` deriving it from `end_date` is the
#     only way EXPIRED can ever be said.

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('companies', '0005_company_logo'),
        ('customers', '0017_sprint154_default_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(help_text='Human reference, CNT-YYYY-NNNN. Gapless per (company, year), assigned at CREATE by contracts.numbering.', max_length=32)),
                ('start_date', models.DateField(help_text='First day the contract is in force.')),
                ('end_date', models.DateField(blank=True, help_text='Last day in force. NULL means open-ended, which is a legal and common shape — do not treat NULL as an error.', null=True)),
                ('lifecycle', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='The stored, operator-chosen part of the status. EXPIRED is NOT storable here — it is derived from end_date by `Contract.status`. See ContractLifecycle.', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=16)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day-of-month the invoice is dated (1..28). Capped at 28 so the day exists in every month — the same reasoning Customer.invoice_day_of_month uses.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('billing_type', models.CharField(choices=[('ADVANCE', 'In advance'), ('ARREARS', 'In arrears')], default='ADVANCE', help_text='ADVANCE bills at the start of the period it covers; ARREARS bills after the period has ended.', max_length=16)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Days from invoice date to due date.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('start_proration', models.BooleanField(default=True, help_text='When on, a contract starting mid-period bills a part period first (and a contract ending mid-period bills a part period last). When off, every period bills in full.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant anchor. Every scoping question resolves through this.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='companies.company')),
                ('customer', models.ForeignKey(help_text='The customer organisation that signed. PROTECT: a customer with a contract cannot be hard-deleted out from under it.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(help_text='PROTECT: a building named on a live contract cannot be hard-deleted out from under it.', on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='buildings.building')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_links', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'contract building',
                'verbose_name_plural': 'contract buildings',
                'ordering': ['building__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='buildings',
            field=models.ManyToManyField(blank=True, help_text='The locations this contract covers. Every building must belong to the SAME company as the contract; the serializer rejects a cross-company id with a 400 and the picker never offers one.', related_name='contracts', through='contracts.ContractBuilding', to='buildings.building'),
        ),
        migrations.CreateModel(
            name='ContractNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_number_sequences', to='companies.company')),
            ],
            options={
                'verbose_name': 'contract number sequence',
                'verbose_name_plural': 'contract number sequences',
                'ordering': ['company_id', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ContractRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Free text — "Oorspronkelijk contract", "Prijsverhoging 2027". Shown as the active revision on the contract.', max_length=200)),
                ('effective_from', models.DateField(help_text='The date this version of the scope takes over. May be in the future; the contract keeps resolving to the previous revision until then.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who authored the revision. Nullable only for the system-authored first revision of a contract created outside a request (fixtures, data migrations).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contract revision',
                'verbose_name_plural': 'contract revisions',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The project, e.g. "Dagelijkse schoonmaak kantoren".', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order; ties break on id.')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budgeted hours for ONE billing period of this contract. The per-period basis is what makes a later comparison against worked hours well-defined.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, help_text="Square metres this project covers. New and additive — the system held square metres nowhere before this sprint (extra_work's SQUARE_METERS is a pricing UNIT, which is a different thing). NULL means not recorded.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="This line's money for ONE billing period, excl. VAT.", max_digits=12)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, help_text="Optional: which of the contract's buildings this project covers. NULL means the contract as a whole. Present so the planned agreed-vs-worked hours comparison has a building to group by; nothing in this sprint reads it for money.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='buildings.building')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.contractrevision')),
            ],
            options={
                'verbose_name': 'contract line',
                'verbose_name_plural': 'contract lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing name, e.g. "Schoonmaak", "Machines".', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Archived types stay on existing contracts but are not offerable for new ones.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order in the pickers; ties break on name.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company that owns this contract type. PROTECT mirrors HourType.company: a Company cannot be hard-deleted while it still owns contract types.', on_delete=django.db.models.deletion.PROTECT, related_name='contract_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'contract type',
                'verbose_name_plural': 'contract types',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(blank=True, help_text="Per-company catalog row. Nullable because a company's catalog may still be empty when its first contract is drafted.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contracttype'),
        ),
        migrations.AddConstraint(
            model_name='contractbuilding',
            constraint=models.UniqueConstraint(fields=('contract', 'building'), name='uniq_contract_building'),
        ),
        migrations.AddConstraint(
            model_name='contractnumbersequence',
            constraint=models.UniqueConstraint(fields=('company', 'year'), name='uniq_contract_number_seq_per_company_year'),
        ),
        migrations.AddIndex(
            model_name='contractrevision',
            index=models.Index(fields=['contract', '-effective_from'], name='contract_rev_effective_idx'),
        ),
        migrations.AddIndex(
            model_name='contractline',
            index=models.Index(fields=['revision', 'sort_order'], name='contract_line_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('company'), name='uniq_contract_type_name_per_company_ci'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'start_date'], name='contract_company_start_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['customer', 'start_date'], name='contract_customer_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('company', 'contract_no'), name='uniq_contract_no_per_company'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle__in', ['DRAFT', 'ACTIVE', 'CANCELLED'])), name='contract_lifecycle_is_storable'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contract_end_after_start'),
        ),
    ]
