# Generated by Django 5.2.17 on 2026-08-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('invoicing', '0005_invoice_granularity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First day of the billed period. Half of the uniqueness key.')),
                ('period_end', models.DateField()),
                ('invoice_date', models.DateField(help_text="The forecast's date for this period. Kept here because `invoicing.Invoice` has no invoice_date column and this sprint does not change its schema.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_invoices', to='contracts.contract')),
                ('invoice', models.OneToOneField(help_text='CASCADE: this row is a CLAIM about an invoice, so it must not outlive it. A deleted invoice releases its period to be generated again, which is the behaviour a hard delete should have.', on_delete=django.db.models.deletion.CASCADE, related_name='contract_period', to='invoicing.invoice')),
                ('revision', models.ForeignKey(help_text='The agreed scope this period was priced from.', on_delete=django.db.models.deletion.PROTECT, related_name='generated_invoices', to='contracts.contractrevision')),
            ],
            options={
                'verbose_name': 'contract invoice',
                'verbose_name_plural': 'contract invoices',
                'ordering': ['-period_start', '-id'],
                'indexes': [models.Index(fields=['contract', '-period_start'], name='contract_invoice_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'period_start'), name='uniq_contract_invoice_per_period')],
            },
        ),
    ]
