# Generated by Django 5.2.17 on 2026-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='standard_slot',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('extra_work', 'Extra Works'), ('machine', 'Machine'), ('other', 'Other')], default='', help_text='Derived from `name`: the standard kind this row is recognised as, or blank for a custom type.', max_length=32),
        ),
    ]
