# Generated by Django 5.2.17 on 2026-08-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_sprint185_building_cost_share'),
        ('companies', '0005_company_logo'),
        ('contracts', '0004_backfill_contract_type_slot'),
        ('customers', '0019_sprint185_customer_address_lifecycle_contact_invoices'),
        ('extra_work', '0037_w13_customer_completion_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='kind',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('EXTRA_WORK', 'Extra work register')], db_index=True, default='STANDARD', help_text='STANDARD is the recurring agreement that raises invoices. EXTRA_WORK is the per-customer register of chargeable work, which never raises one -- see `ContractKind`.', max_length=16),
        ),
        migrations.AddField(
            model_name='contractline',
            name='extra_work',
            field=models.ForeignKey(blank=True, help_text="W16 -- the chargeable job this line MIRRORS, on an EXTRA_WORK register. NULL on every STANDARD contract line, where the line is the agreement itself and there is no job behind it yet.\n\nThe reference system's equivalent lines carry no such link: an operator retypes a description and an amount, so its register can and does disagree with its invoices. This FK is what makes ours a projection rather than a second set of books -- `sync_extra_work_register` rebuilds the amount from `_earned_amounts`, the same rule the invoice reads.\n\nCASCADE, not PROTECT: a register line is a mirror of the job, so a deleted job must take its reflection with it. PROTECT would make the register able to block a delete that has nothing to do with it.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_register_lines', to='extra_work.extraworkrequest'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'EXTRA_WORK')), fields=('company', 'customer'), name='uniq_extra_work_register_per_customer'),
        ),
    ]
