# Generated by Django 5.2.16 on 2026-08-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_kind_contractline_extra_work_and_more'),
        ('customers', '0019_sprint185_customer_address_lifecycle_contact_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractline',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Optional: which of the CUSTOMER'S department labels this line serves (the per-customer list Extra Work already uses). The serializer rejects a department of any other customer — a cross-customer label on a contract line is a tenant-scoping violation. SET_NULL: deleting a label must not take agreed scope lines with it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_lines', to='customers.department'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='frequency_per_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text="How many times per YEAR this line's work is performed (the reference system's `frequency`). NULL means the line is not planned by count. The 52-week planning grid of a later sprint buckets on exactly this number — it is a COUNT of performances, never a divisor or multiplier for `amount`, which stays per billing period.", null=True),
        ),
        migrations.AddField(
            model_name='contractline',
            name='norm',
            field=models.CharField(blank=True, default='', help_text="The operator's norm / spec note for this line, e.g. '180 m2/uur'. Free text; nothing computes from it.", max_length=200),
        ),
    ]
