# Generated by Django 5.2.13 on 2026-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
