# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticketattachment_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_no",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
