# Generated by Django 5.2.13 on 2026-05-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_no_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_first_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(choices=[('ON_TRACK', 'On track'), ('AT_RISK', 'At risk'), ('BREACHED', 'Breached'), ('COMPLETED', 'Completed'), ('HISTORICAL', 'Historical')], db_index=True, default='ON_TRACK', max_length=16),
        ),
    ]
