# Generated by Django 5.2.14 on 2026-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_staffassignmentrequest_ticketstaffassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatushistory',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketstatushistory',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
