# Generated by Django 5.2.14 on 2026-05-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0003_request_items_and_routing'),
        ('tickets', '0007_ticketstatushistory_is_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='extra_work_request_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_tickets', to='extra_work.extraworkrequestitem'),
        ),
    ]
