# Generated by Django 5.2.14 on 2026-05-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0004_proposal_models'),
        ('tickets', '0008_ticket_extra_work_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='proposal_line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_tickets_for_proposal_line', to='extra_work.proposalline'),
        ),
    ]
