# Generated by Django 5.2.14 on 2026-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_waiting_manager_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='message_type',
            field=models.CharField(choices=[('PUBLIC_REPLY', 'Public Reply'), ('INTERNAL_NOTE', 'Internal Note (provider-internal)'), ('STAFF_OPERATIONAL', 'Staff Operational Note'), ('STAFF_COMPLETION', 'Staff Completion Note')], default='PUBLIC_REPLY', max_length=32),
        ),
    ]
