# Generated by Django 5.2.14 on 2026-05-31 13:49
#
# Sprint 6A — collapse operational spawn to exactly ONE Ticket per
# ExtraWorkRequest. Adds the canonical `Ticket.extra_work_request` FK
# and backfills it for every existing ticket from whichever legacy
# link it carries (cart-item FK chain or proposal-line FK chain).
#
# No DB unique constraint is added: historical data has multiple
# tickets per request, so every such ticket simply gets the same
# `extra_work_request` link. Idempotency (one-ticket-per-request going
# forward) is enforced in the spawn helpers + tests, not in the schema.

import django.db.models.deletion
from django.db import migrations, models


def backfill_extra_work_request(apps, schema_editor):
    """For every Ticket with a NULL `extra_work_request`, resolve the
    parent ExtraWorkRequest from its legacy link:

      * `extra_work_request_item` set -> the item's
        `extra_work_request_id`.
      * else `proposal_line` set -> the proposal's
        `extra_work_request_id`.

    Historical tickets are never deleted or merged — multiple tickets
    per request all simply get the same `extra_work_request` link.
    """
    Ticket = apps.get_model("tickets", "Ticket")

    qs = Ticket.objects.filter(extra_work_request_id__isnull=True)

    # Cart-item path.
    for ticket_id, ew_id in (
        qs.filter(extra_work_request_item_id__isnull=False)
        .values_list("id", "extra_work_request_item__extra_work_request_id")
    ):
        if ew_id is not None:
            Ticket.objects.filter(pk=ticket_id).update(
                extra_work_request_id=ew_id
            )

    # Proposal-line path (only rows still NULL after the cart-item pass).
    for ticket_id, ew_id in (
        Ticket.objects.filter(
            extra_work_request_id__isnull=True,
            proposal_line_id__isnull=False,
        ).values_list(
            "id", "proposal_line__proposal__extra_work_request_id"
        )
    ):
        if ew_id is not None:
            Ticket.objects.filter(pk=ticket_id).update(
                extra_work_request_id=ew_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('extra_work', '0009_sprint3b_service_company_not_null'),
        ('tickets', '0011_b7_message_type_four_tier_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='extra_work_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_tickets', to='extra_work.extraworkrequest'),
        ),
        migrations.RunPython(
            backfill_extra_work_request,
            migrations.RunPython.noop,
        ),
    ]
