# Generated by Django 5.2.14 on 2026-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_extra_work_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_MANAGER_REVIEW', 'Waiting Manager Review'), ('WAITING_CUSTOMER_APPROVAL', 'Waiting Customer Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('REOPENED_BY_ADMIN', 'Reopened by Admin'), ('CONVERTED_TO_EXTRA_WORK', 'Converted to Extra Work')], default='OPEN', max_length=64),
        ),
    ]
