# Generated by Django 5.2.14 on 2026-05-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reschedule_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rescheduled_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule_status',
            field=models.CharField(choices=[('UNSCHEDULED', 'Unscheduled'), ('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled')], default='UNSCHEDULED', max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_window_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
