# Generated by Django 5.2.14 on 2026-06-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_work', '0001_initial'),
        ('tickets', '0015_ticketmanagerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='planned_occurrence',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='planned_work.plannedoccurrence'),
        ),
    ]
