# Generated by Django 5.2.14 on 2026-06-02 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticket_planned_occurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='assignment_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_slots_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='completion_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='slot_status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('UNABLE_TO_COMPLETE', 'Unable to complete'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=24),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='time_window_label',
            field=models.CharField(blank=True, default='', help_text='Free-text window hint, e.g. morning / afternoon / evening / 08:00-10:00.', max_length=64),
        ),
        migrations.AddField(
            model_name='ticketstaffassignment',
            name='unable_to_complete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='ticketstaffassignment',
            index=models.Index(fields=['user', 'scheduled_start_at'], name='tickets_tic_user_id_5ef189_idx'),
        ),
    ]
