# Generated by Django 5.2.14 on 2026-06-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticketstaffassignment_assignment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='staff_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketstaffassignment'),
        ),
    ]
