# Generated by Django 5.2.14 on 2026-06-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticketattachment_staff_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketstaffassignment',
            unique_together=set(),
        ),
    ]
