# Generated by Django 5.2.14 on 2026-06-06 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticket_auto_complete_on_subtasks_subtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='directed_to',
            field=models.ManyToManyField(blank=True, related_name='directed_ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='visibility_mode',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RESTRICTED', 'Restricted')], db_index=True, default='NORMAL', max_length=16),
        ),
    ]
