# Generated by Django 5.2.14 on 2026-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticketmessage_directed_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='message_type',
            field=models.CharField(choices=[('PUBLIC_REPLY', 'Public Reply'), ('INTERNAL_NOTE', 'Internal Note (provider-internal)'), ('STAFF_OPERATIONAL', 'Staff Operational Note'), ('STAFF_COMPLETION', 'Staff Completion Note'), ('CUSTOMER_INTERNAL', 'Customer Internal Note')], default='PUBLIC_REPLY', max_length=32),
        ),
    ]
