# Generated by Django 5.2.16 on 2026-08-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_alter_ticketmessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('REPORT', 'Melding / Report'), ('COMPLAINT', 'Klacht / Complaint'), ('REQUEST', 'Verzoek / Request'), ('SUGGESTION', 'Suggestie / Suggestion'), ('QUOTE_REQUEST', 'Offerteaanvraag / Quote Request'), ('OTHER', 'Overig / Other')], default='REPORT', max_length=32),
        ),
    ]
