"""
Sprint 184 §3 — a melding can carry the customer's wanted date.

Additive: one nullable DateField with no default beyond NULL, no data
touched. NULL means the customer did not say — which has to stay
distinguishable from a date they chose, and is why this is nullable
rather than defaulting to the creation day.

It is a WISH, not a deadline: nothing in the overdue rules reads it. The
provider's commitment stays `ExtraWorkRequest.deadline`, provider-only.
"""
# Generated by Django 5.2.17 on 2026-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_sprint180_status_history_system_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_wanted_date',
            field=models.DateField(blank=True, default=None, help_text='Sprint 184 — the date the CUSTOMER would like this done. A wish, not a commitment: it never decides whether the ticket is late. Carried into ExtraWorkRequest.preferred_date on conversion.', null=True),
        ),
    ]
