# Generated by Django 5.2.17 on 2026-08-16 07:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_logo'),
        ('tickets', '0025_sprint184_customer_wanted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing name, e.g. "Sanitair", "Glasbewassing".', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Archived categories stay on the meldingen that carry them but are not offerable for new ones.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order in the pickers; ties break on name.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company that owns this category. PROTECT mirrors BuildingType.company: a Company cannot be hard-deleted while it still owns categories.', on_delete=django.db.models.deletion.PROTECT, related_name='work_categories', to='companies.company')),
            ],
            options={
                'verbose_name': 'work category',
                'verbose_name_plural': 'work categories',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, default=None, help_text="Sprint 185 — the kind of WORK this melding is about, from the company's own catalog. Independent of `type`, which says what kind of MESSAGE it is.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.workcategory'),
        ),
        migrations.AddConstraint(
            model_name='workcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('company'), name='uniq_work_category_name_per_company_ci'),
        ),
    ]
