# Generated by Django 5.2.17 on 2026-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_w4p_upload_visibility_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('WAITING_MANAGER_REVIEW', 'Waiting Manager Review'), ('WAITING_CUSTOMER_APPROVAL', 'Waiting Customer Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('REOPENED_BY_ADMIN', 'Reopened by Admin'), ('CONVERTED_TO_EXTRA_WORK', 'Converted to Extra Work')], default='OPEN', max_length=64),
        ),
    ]
