# Generated by Django 5.2.16 on 2026-08-26 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_w13_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('L2_MANAGERS', 'Deadline passed: assigned managers'), ('L2_ESCALATED', 'Deadline still passed: managers and admins'), ('L3_QUARANTINE', 'Quarantine: provider admins')], max_length=16)),
                ('anchor_date', models.DateField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_ids', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='tickets.ticket')),
            ],
            options={
                'ordering': ['notified_at', 'id'],
                'indexes': [models.Index(fields=['ticket', 'step'], name='tickets_tic_ticket__b0a285_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'step', 'anchor_date'), name='ticket_escalation_once_per_step_and_anchor')],
            },
        ),
    ]
