# Generated by Django 5.2.16 on 2026-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_w_late_ticket_escalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='planned_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='planned_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='time_window_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
