# Generated by Django 5.2.16 on 2026-07-20 15:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('companies', '0005_company_logo'),
        ('customers', '0012_customer_contract_pdf_customer_invoice_day_rule_and_more'),
        ('extra_work', '0016_proposalline_custom_unit_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent')], db_index=True, default='DRAFT', max_length=16)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('optional_fee_label', models.CharField(blank=True, default='', max_length=255)),
                ('optional_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('period_month', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='buildings.building')),
                ('company', models.ForeignKey(help_text='Provider company that issues this invoice (tenant anchor).', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('reverses', models.ForeignKey(blank=True, help_text='The original invoice this one reverses; NULL unless is_reversal. A reversal is terminal (cannot reverse a reversal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('period_month', models.PositiveIntegerField(blank=True, null=True)),
                ('performed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='extra_work.extraworkrequest')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['invoice', 'ordering', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status'], name='invoicing_i_company_1397b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='invoicing_i_custome_f28b76_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'year'], name='invoicing_i_company_34c65a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deleted_at'], name='invoicing_i_deleted_af07be_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_invoice_company_number'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice'], name='invoicing_i_invoice_7eb31c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['extra_work'], name='invoicing_i_extra_w_07aa8e_idx'),
        ),
    ]
