# Generated by Django 5.2.16 on 2026-07-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_logo'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_number_sequences', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year'], name='invoicing_i_company_02c509_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'year'), name='uniq_invoice_seq_company_year')],
            },
        ),
    ]
