# Generated by Django 5.2.16 on 2026-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoicenumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='summary_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
