# Generated by Django 5.2.16 on 2026-07-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_invoice_granularity_default'),
        ('invoicing', '0003_invoice_summary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.department'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.worktype'),
        ),
    ]
