# Generated by Django 5.2.16 on 2026-07-28 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('companies', '0005_company_logo'),
        ('customers', '0016_alter_customer_invoice_granularity_default'),
        ('invoicing', '0004_invoice_department_invoice_work_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='granularity',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer-level'), ('PER_BUILDING', 'Per building'), ('PER_BUILDING_DEPARTMENT_WORK_TYPE', 'Per building, department & work type')], max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('reverses',), name='uniq_live_reversal_per_original'),
        ),
    ]
