# Generated by Django 5.2.17 on 2026-08-14 13:06

import invoicing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoice_granularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='The frozen invoice PDF, written at SEND. NULL means not yet frozen: every DRAFT and ISSUED invoice, plus any invoice sent before this field existed (those freeze lazily on first access, or in bulk via `manage.py freeze_invoice_pdfs`).', max_length=255, null=True, upload_to=invoicing.models.invoice_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_sha256',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
    ]
