# Generated by Django 5.2.16 on 2026-08-06 13:21
#
# Sprint 152 — the employee-hours module's initial schema. Purely
# ADDITIVE: three new tables, no existing table altered, no data
# migration, nothing to backfill.
#
# Note the `uniq_hour_type_name_per_company_ci` constraint is created in
# THIS migration, alongside the table. `ServiceCategory` and
# `ManagedUnit` reached the same constraint through a nullable-column /
# backfill / NOT NULL sequence, because they were retrofitting a
# company FK onto rows that already existed. There is nothing here to
# retrofit, so there is never a window in which the table exists without
# its uniqueness rule.

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('companies', '0005_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing name, e.g. "Normale uren", "Overwerk".', max_length=128)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Weighting factor for an hour of this kind (1.00 = normal, 1.50 = overtime). 0.00 is legal — unpaid leave. This is a weight, never a wage: nothing here computes money.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9.99'))])),
                ('is_active', models.BooleanField(default=True, help_text='Archived types stay on existing entries but are not offerable for new ones.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order in the pickers; ties break on name.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company that owns this hour type. PROTECT mirrors ServiceCategory.company: a Company cannot be hard-deleted while it still owns hour types.', on_delete=django.db.models.deletion.PROTECT, related_name='hour_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'hour type',
                'verbose_name_plural': 'hour types',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day worked. Past AND future dates are allowed.')),
                ('iso_year', models.PositiveIntegerField(help_text='Derived from `date` on save; never client-supplied.')),
                ('iso_week', models.PositiveIntegerField(help_text='Derived from `date` on save; never client-supplied.')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked on this entry (0.25 - 24.00).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('multiplier_snapshot', models.DecimalField(decimal_places=2, help_text='Copy of hour_type.multiplier at write time. Every weighted total reads THIS, never the live multiplier.', max_digits=4)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, help_text="Optional: where the hours were worked. Must belong to the entry's own company. SET_NULL so retiring a building never destroys an hours record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='buildings.building')),
                ('company', models.ForeignKey(help_text="Denormalized tenant anchor, resolved from the employee's provider-company membership at write time.", on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='companies.company')),
                ('created_by', models.ForeignKey(help_text="Who filed the entry. Differs from `employee` when an admin records hours on someone's behalf.", on_delete=django.db.models.deletion.PROTECT, related_name='created_time_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The provider-side employee whose hours these are. Must hold an active membership in `company` with a provider role (STAFF / BUILDING_MANAGER / COMPANY_ADMIN) — never a customer-side user, never a SUPER_ADMIN.', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('hour_type', models.ForeignKey(help_text='PROTECT: an hour type in use can never be hard-deleted, only archived.', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='timesheets.hourtype')),
            ],
            options={
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeekLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.PositiveIntegerField()),
                ('iso_week', models.PositiveIntegerField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_week_locks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='week_locks', to='companies.company')),
            ],
            options={
                'verbose_name': 'week lock',
                'verbose_name_plural': 'week locks',
                'ordering': ['-iso_year', '-iso_week', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='hourtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('company'), name='uniq_hour_type_name_per_company_ci'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['company', 'date'], name='ts_entry_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', 'date'], name='ts_entry_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['company', 'iso_year', 'iso_week'], name='ts_entry_company_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklock',
            constraint=models.UniqueConstraint(fields=('company', 'iso_year', 'iso_week'), name='uniq_week_lock_per_company_week'),
        ),
    ]
