# Generated by Django 5.2.16 on 2026-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourtype',
            name='standard_slot',
            field=models.CharField(blank=True, choices=[('normal_hours', 'Normal hours'), ('overtime', 'Overtime'), ('weekend', 'Weekend hours'), ('public_holiday', 'Public holiday'), ('sick_leave', 'Sick leave'), ('vacation', 'Vacation')], default='', help_text="Derived from `name`: the standard kind this row is recognised as, or blank for a custom type. Lets the UI show a standard name in each reader's own language while `name` stays a single operator-typed column.", max_length=32),
        ),
    ]
