# Generated by Django 5.2.17 on 2026-08-11 19:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('companies', '0005_company_logo'),
        ('timesheets', '0003_backfill_standard_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(help_text='First day this agreement is in force.')),
                ('valid_to', models.DateField(blank=True, help_text='Last day in force. NULL means open-ended.', null=True)),
                ('monday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('tuesday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('wednesday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('thursday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('friday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('saturday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('sunday', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SAVED', 'Saved'), ('APPROVED', 'Approved')], default='DRAFT', help_text='See ContractHoursStatus for the transitions and who may make them.', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Who approved it. Cleared when a row is reopened.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_hours', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, help_text="Where the agreed hours are worked. NULL is allowed for an agreement not tied to one location, and reads as 'no building' rather than being dropped from a report.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_hours', to='buildings.building')),
                ('company', models.ForeignKey(help_text="Denormalized tenant anchor, resolved from the employee's provider-company membership at write time — the same shape TimeEntry.company uses, and for the same reason.", on_delete=django.db.models.deletion.PROTECT, related_name='contract_hours', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_hours', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The provider-side employee this agreement is about. Never a customer-side user, never a SUPER_ADMIN.', on_delete=django.db.models.deletion.PROTECT, related_name='contract_hours', to=settings.AUTH_USER_MODEL)),
                ('hour_type', models.ForeignKey(help_text='PROTECT: a type in use can be archived, never deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='contract_hours', to='timesheets.hourtype')),
            ],
            options={
                'verbose_name': 'contract hours',
                'verbose_name_plural': 'contract hours',
                'ordering': ['building__name', 'employee__full_name', '-valid_from', '-id'],
                'indexes': [models.Index(fields=['company', '-valid_from'], name='ch_company_valid_idx'), models.Index(fields=['employee', 'building', '-valid_from'], name='ch_employee_building_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='contract_hours_valid_to_after_from')],
            },
        ),
    ]
