# Generated by Django 5.2.17 on 2026-08-11 22:17

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_logo'),
        ('timesheets', '0004_contracthours'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing name, e.g. "Vast werk", "Meerwerk".', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Archived types stay on existing rows but are not offerable for new ones — the HourType rule, for the same reason: deleting one would rewrite what an agreement said.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order in the pickers; ties break on name.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company that owns this work type. PROTECT mirrors HourType.company: a Company cannot be hard-deleted while it still owns work types.', on_delete=django.db.models.deletion.PROTECT, related_name='work_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'work type',
                'verbose_name_plural': 'work types',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contracthours',
            name='work_type',
            field=models.ForeignKey(blank=True, help_text='What KIND of work is agreed. NULL for rows written before the catalog existed, and for a company that keeps no work types — not a default, because a default here would be a claim nobody made.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_hours', to='timesheets.worktype'),
        ),
        migrations.AddConstraint(
            model_name='worktype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('company'), name='uniq_work_type_name_per_company_ci'),
        ),
    ]
