# Generated by Django 5.2.17 on 2026-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_worktype_contracthours_work_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='standard_slot',
            field=models.CharField(blank=True, default='', help_text='Derived from `name`: the standard kind this row is recognised as, or blank for a custom type.', max_length=32),
        ),
    ]
