# Generated by Django 5.2.17 on 2026-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_backfill_work_type_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourtype',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short payroll code for this hour type, e.g. "GU". Printed beside the name on the worker hour report.', max_length=16),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_authorised',
            field=models.BooleanField(default=False, help_text='Reference column MACHT. Meaning unconfirmed — modelled as a flag until the owner says otherwise.'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='travel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Travel costs claimed for this entry, in euros. NULL means none was claimed, which is different from a claim of 0.00.', max_digits=9, null=True),
        ),
    ]
