# Generated by Django 5.2.17 on 2026-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_hourtype_code_timeentry_is_authorised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='The id within `source_type`. NOT a foreign key: `timesheets` may not import `tickets` or `extra_work`. An id that no longer resolves renders as a plain label.', null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='source_type',
            field=models.CharField(choices=[('CONTRACT', 'Contract'), ('EXTRA_WORK', 'Extra work'), ('TICKET', 'Ticket'), ('OTHER', 'Other')], default='OTHER', help_text='Which kind of work produced this hour. OTHER is the default so an existing row keeps its meaning rather than being backfilled with a guess.', max_length=16),
        ),
    ]
