# Generated by Django 5.2.17 on 2026-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_timeentry_source_id_timeentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthours',
            name='auto_fill',
            field=models.BooleanField(default=False, help_text="Fill this person's weekly sheet from this agreement, for every week inside the validity window. The filled rows are ordinary TimeEntry rows and stay editable until the week is closed."),
        ),
    ]
