# Generated by Django 5.2.13 on 2026-05-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='buildings.building'),
        ),
        migrations.CreateModel(
            name='CustomerBuildingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_memberships', to='buildings.building')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_memberships', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'building'], name='customers_c_custome_903af3_idx')],
                'unique_together': {('customer', 'building')},
            },
        ),
        migrations.CreateModel(
            name='CustomerUserBuildingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_user_access', to='buildings.building')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_access', to='customers.customerusermembership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership', 'building'], name='customers_c_members_2c8462_idx')],
                'unique_together': {('membership', 'building')},
            },
        ),
    ]
