# Generated by Django 5.2.14 on 2026-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_backfill_building_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='show_assigned_staff_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='show_assigned_staff_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='show_assigned_staff_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruserbuildingaccess',
            name='access_role',
            field=models.CharField(choices=[('CUSTOMER_USER', 'Customer user'), ('CUSTOMER_LOCATION_MANAGER', 'Customer location manager'), ('CUSTOMER_COMPANY_ADMIN', 'Customer company admin')], default='CUSTOMER_USER', max_length=32),
        ),
        migrations.AddField(
            model_name='customeruserbuildingaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruserbuildingaccess',
            name='permission_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
