# Generated by Django 5.2.14 on 2026-05-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_show_assigned_staff_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_assigned_staff_name', models.BooleanField(default=True)),
                ('show_assigned_staff_email', models.BooleanField(default=True)),
                ('show_assigned_staff_phone', models.BooleanField(default=True)),
                ('customer_users_can_create_tickets', models.BooleanField(default=True)),
                ('customer_users_can_approve_ticket_completion', models.BooleanField(default=True)),
                ('customer_users_can_create_extra_work', models.BooleanField(default=True)),
                ('customer_users_can_approve_extra_work_pricing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer company policy',
                'verbose_name_plural': 'customer company policies',
            },
        ),
    ]
