# Generated by Django 5.2.14 on 2026-06-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('customers', '0007_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBuildingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('OPERATIONS', 'Operations'), ('BILLING', 'Billing'), ('EMERGENCY', 'Emergency')], default='GENERAL', max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('customer', 'user'), name='uniq_contact_user_per_customer'),
        ),
        migrations.AddField(
            model_name='contactbuildinglink',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_links', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='contactbuildinglink',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_links', to='customers.contact'),
        ),
        migrations.AddIndex(
            model_name='contactbuildinglink',
            index=models.Index(fields=['contact', 'building'], name='customers_c_contact_1daebc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactbuildinglink',
            unique_together={('contact', 'building')},
        ),
    ]
