# Generated by Django 5.2.16 on 2026-07-17 17:58

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_add_is_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=customers.models.customer_logo_upload_path),
        ),
    ]
