# Generated by Django 5.2.16 on 2026-07-20 15:45

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contract_pdf',
            field=models.FileField(blank=True, help_text='Informational contract PDF only; zero behavioural effect.', null=True, upload_to=customers.models.customer_contract_upload_path),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_day_rule',
            field=models.CharField(blank=True, choices=[('FIRST_OF_MONTH', 'First of month'), ('LAST_OF_MONTH', 'Last of month')], default='', help_text="Informational billing-day rule; drives the 'who's due' list, gates nothing.", max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_granularity_default',
            field=models.CharField(choices=[('CUSTOMER', 'Customer-level'), ('PER_BUILDING', 'Per building')], default='CUSTOMER', help_text='Default invoice granularity (customer-level vs per-building) for Phase 2 generation.', max_length=16),
        ),
    ]
