# Generated by Django 5.2.16 on 2026-07-21 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_contract_pdf_customer_invoice_day_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific billing day-of-month (1..28); takes precedence over invoice_day_rule. NULL falls back to the first/last rule.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
