# Generated by Django 5.2.16 on 2026-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_invoice_day_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompanypolicy',
            name='customer_users_can_manage_documents',
            field=models.BooleanField(default=True),
        ),
    ]
