# Generated by Django 5.2.16 on 2026-07-27 23:32

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customercompanypolicy_customer_users_can_manage_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Archiving (is_active=False) retires a label from the everyday picker WITHOUT breaking Extra Work rows that already reference it — the soft-retire path when a hard delete is refused by the PROTECT on ExtraWorkRequest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Customer that owns this label. CASCADE: the label list is pure per-customer metadata with no independent lifecycle, so it is removed with the customer.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='customers.customer')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('customer'), name='uniq_customers_department_name_per_customer_ci')],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Archiving (is_active=False) retires a label from the everyday picker WITHOUT breaking Extra Work rows that already reference it — the soft-retire path when a hard delete is refused by the PROTECT on ExtraWorkRequest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Customer that owns this label. CASCADE: the label list is pure per-customer metadata with no independent lifecycle, so it is removed with the customer.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='customers.customer')),
            ],
            options={
                'verbose_name': 'work type',
                'verbose_name_plural': 'work types',
                'ordering': ['name', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('customer'), name='uniq_customers_worktype_name_per_customer_ci')],
            },
        ),
    ]
