# Generated by Django 5.2.16 on 2026-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_department_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invoice_granularity_default',
            field=models.CharField(choices=[('CUSTOMER', 'Customer-level'), ('PER_BUILDING', 'Per building'), ('PER_BUILDING_DEPARTMENT_WORK_TYPE', 'Per building, department & work type')], default='CUSTOMER', help_text='Default invoice granularity for Phase 2 generation.', max_length=40),
        ),
    ]
