"""Sprint 185 §1 §2 §3 — the customer record grows an address, a
lifecycle and an invoice recipient.

ADDITIVE ONLY. Every column here holds data the system has never had, and
none of it changes what an existing row MEANS:

  * the four address columns default to "" — no customer had an address,
    so every existing row correctly says "not filled in";
  * `Contact.receives_invoices` defaults to False — nobody was receiving
    invoices, because there was no mechanism to receive them;
  * `Customer.lifecycle` is backfilled FAITHFULLY from `is_active`
    (True -> ACTIVE, False -> CHURNED) rather than left on its default,
    because a deactivated customer reading "Active" would be the
    migration asserting something nobody said.

**Nobody's access changes.** `is_active` is untouched and remains the only
thing access is decided by; `lifecycle` is descriptive. The reverse is a
genuine no-op for the same reason — dropping a descriptive column cannot
change who may log in.
"""

# Generated by Django 5.2.17 on 2026-08-15 22:45

from django.db import migrations, models


def lifecycle_from_is_active(apps, schema_editor):
    """True -> ACTIVE, False -> CHURNED. Two updates, not a row loop.

    CHURNED rather than PROSPECT for the inactive rows: a customer that
    was switched off is a relationship that ENDED, not one that never
    started. Neither is provably right for every historic row — nobody
    recorded which — but "ended" is the only reading consistent with the
    row having existed and been active at some point.
    """
    Customer = apps.get_model("customers", "Customer")
    Customer.objects.filter(is_active=True).update(lifecycle="ACTIVE")
    Customer.objects.filter(is_active=False).update(lifecycle="CHURNED")


def noop_reverse(apps, schema_editor):
    """Nothing to undo: the column is dropped by the reverse of AddField,
    and it never drove any behaviour to restore."""


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_sprint182_billing_target_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='receives_invoices',
            field=models.BooleanField(default=False, help_text='Sprint 185 §2 — send this contact the invoice when one is sent. Requires an e-mail address; a contact with none is skipped and the skip is reported.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='lifecycle',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('NOTICE', 'Notice period'), ('CHURNED', 'Churned')], db_index=True, default='ACTIVE', help_text='Where the relationship is. DESCRIPTIVE ONLY — `is_active` decides access, this decides what the screens say.', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(
            lifecycle_from_is_active,
            noop_reverse,
        ),
    ]
