# Generated by Django 5.2.14 on 2026-06-01 14:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
        ('companies', '0003_sprint3b_provider_admin_catalog_policies'),
        ('customers', '0007_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(db_index=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('TICKET_CREATED', 'Ticket created'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('missed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_occurrences', to='buildings.building')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_occurrences', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_occurrences', to='customers.customer')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='PlannedOccurrenceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_occurrence_status_changes', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='planned_work.plannedoccurrence')),
            ],
            options={
                'verbose_name_plural': 'Planned occurrence status history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('time_window_label', models.CharField(blank=True, default='', max_length=64)),
                ('pricing_mode', models.CharField(choices=[('CONTRACT_INCLUDED', 'Contract included'), ('FIXED', 'Fixed price'), ('HOURLY', 'Hourly (reserved — no actual-hours plumbing in 11B)')], default='CONTRACT_INCLUDED', max_length=24)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='buildings.building')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recurring_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='recurring_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='planned_work.recurringjob'),
        ),
        migrations.CreateModel(
            name='RecurringJobDefaultManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_managers', to='planned_work.recurringjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_job_default_managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringJobDefaultStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_staff', to='planned_work.recurringjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_job_default_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='plannedoccurrence',
            index=models.Index(fields=['status', 'planned_date'], name='planned_wor_status_2ae770_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedoccurrence',
            index=models.Index(fields=['building', 'planned_date'], name='planned_wor_buildin_94acac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedoccurrence',
            unique_together={('recurring_job', 'planned_date')},
        ),
        migrations.AlterUniqueTogether(
            name='recurringjobdefaultmanager',
            unique_together={('recurring_job', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='recurringjobdefaultstaff',
            unique_together={('recurring_job', 'user')},
        ),
    ]
