# Generated by Django 5.2.14 on 2026-06-02 22:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedoccurrence',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='preferred_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='pricing_mode',
            field=models.CharField(choices=[('CONTRACT_INCLUDED', 'Contract included'), ('FIXED', 'Fixed price'), ('HOURLY', 'Hourly (reserved — no actual-hours plumbing in 11B)')], default='CONTRACT_INCLUDED', max_length=24),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='time_window_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='vat_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
    ]
