# Generated by Django 5.2.14 on 2026-06-02 22:05

from decimal import Decimal
from django.db import migrations, models


# Fields snapshotted from the parent RecurringJob onto each occurrence.
_SNAPSHOT_FIELDS = (
    "pricing_mode",
    "fixed_price",
    "vat_pct",
    "preferred_start_time",
    "time_window_label",
)


def backfill_occurrence_snapshots(apps, schema_editor):
    """Copy the parent RecurringJob's pricing + schedule-window values onto
    every PRE-EXISTING PlannedOccurrence row.

    The AddField operations above default `pricing_mode` to
    CONTRACT_INCLUDED, `fixed_price` to NULL, etc. — so without this backfill
    an existing FIXED-price occurrence would serialise with null billable
    totals (its snapshot would not reflect the job it was generated from).
    This freezes each existing occurrence to its parent job's current values,
    matching what generation now writes for new occurrences. Idempotent and
    re-runnable; uses the historical models via apps.get_model.
    """
    PlannedOccurrence = apps.get_model("planned_work", "PlannedOccurrence")
    for occurrence in (
        PlannedOccurrence.objects.select_related("recurring_job").iterator()
    ):
        job = occurrence.recurring_job
        for field in _SNAPSHOT_FIELDS:
            setattr(occurrence, field, getattr(job, field))
        occurrence.save(update_fields=list(_SNAPSHOT_FIELDS))


class Migration(migrations.Migration):

    dependencies = [
        ('planned_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedoccurrence',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='preferred_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='pricing_mode',
            field=models.CharField(choices=[('CONTRACT_INCLUDED', 'Contract included'), ('FIXED', 'Fixed price'), ('HOURLY', 'Hourly (reserved — no actual-hours plumbing in 11B)')], default='CONTRACT_INCLUDED', max_length=24),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='time_window_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='plannedoccurrence',
            name='vat_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
        # Backfill existing occurrences from their parent job so historical
        # rows become correct frozen snapshots. Reverse is a no-op (the
        # AddField reversals drop the columns anyway).
        migrations.RunPython(
            backfill_occurrence_snapshots, migrations.RunPython.noop
        ),
    ]
