# Generated by Django 5.2.14 on 2026-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_work', '0003_recurring_day_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedoccurrence',
            name='is_ad_hoc',
            field=models.BooleanField(default=False),
        ),
    ]
