# Generated by Django 5.2.16 on 2026-08-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_invoice_granularity_default'),
        ('extra_work', '0027_sprint144_request_category_and_labels'),
        ('planned_work', '0004_plannedoccurrence_is_ad_hoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringjob',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='customers.department'),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='price_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='extra_work.customerpricefolder'),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='extra_work.servicecategory'),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_jobs', to='customers.worktype'),
        ),
    ]
