# Generated by Django 5.2.16 on 2026-08-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractline_department_and_more'),
        ('planned_work', '0005_sprint144_request_category_and_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringjob',
            name='contract_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_jobs', to='contracts.contractline'),
        ),
    ]
