# Generated by Django 5.2.16 on 2026-07-27 18:51

import django.db.models.deletion
import django.db.models.functions.text
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0013_invoice_day_of_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('system_slug', models.CharField(blank=True, default='', max_length=64)),
                ('origin', models.CharField(choices=[('PROVIDER', 'Provider'), ('CUSTOMER', 'Customer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_document_folders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='customers.customer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveIntegerField()),
                ('origin', models.CharField(choices=[('PROVIDER', 'Provider'), ('CUSTOMER', 'Customer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(models.F('customer'), django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', True)), name='uniq_doc_folder_root_name_per_customer_ci'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(models.F('customer'), models.F('parent'), django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', False)), name='uniq_doc_folder_child_name_per_parent_ci'),
        ),
    ]
