# Generated by Django 5.2.14 on 2026-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='provider_admin_may_manage_customer_company_admins',
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Super Admin-controlled policy. When True (default), a "
                    "Provider Company Admin of this provider company may "
                    "manage Customer Company Admin users on this company's "
                    "customers (create, grant, promote, edit, demote, "
                    "revoke, delete). When False, only Super Admin may. "
                    "B4 lower-user management (Customer User / Customer "
                    "Location Manager) is not affected by this toggle."
                ),
            ),
        ),
    ]
