# Generated by Django 5.2.14 on 2026-05-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_b5_provider_admin_may_manage_customer_company_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='provider_admin_may_manage_catalog',
            field=models.BooleanField(default=True, help_text='Sprint 3B — Super Admin-controlled policy. When True (default), a Provider Company Admin of this provider company may manage the provider service catalog (create/update/archive Service + ServiceCategory) for this company. When False, only Super Admin may. Building Manager / Staff / Customer-side users are blocked regardless of this toggle.'),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_admin_may_manage_customer_prices',
            field=models.BooleanField(default=True, help_text='Sprint 3B — Super Admin-controlled policy. When True (default), a Provider Company Admin of this provider company may create / update / archive customer-specific service prices (CustomerServicePrice) for any customer under this provider company. When False, only Super Admin may.'),
        ),
    ]
