# Generated by Django 5.2.14 on 2026-06-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_sprint3b_provider_admin_catalog_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='provider_admin_may_quote_override_start',
            field=models.BooleanField(default=False, help_text='Sprint 14E — DANGEROUS Super Admin-controlled grant (default OFF). When True, a Provider Company Admin / Building Manager of this provider company may bypass customer quote approval and start work from a REQUEST_QUOTE proposal after entering pricing (direct-publish). When False, only Super Admin may. Backs the provider.extra_work.quote_override_start permission key; every use is HIGH-severity audited.'),
        ),
    ]
