# Generated by Django 5.2.16 on 2026-07-17 17:58

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_provider_admin_may_quote_override_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_upload_path),
        ),
    ]
