from django.urls import path

from .views import (
    AgeBucketsView,
    ManagerThroughputView,
    SLABreachRateOverTimeView,
    SLADistributionView,
    StatusDistributionView,
    TicketsByBuildingCSVView,
    TicketsByBuildingPDFView,
    TicketsByBuildingView,
    TicketsByCustomerCSVView,
    TicketsByCustomerPDFView,
    TicketsByCustomerView,
    TicketsByTypeCSVView,
    TicketsByTypePDFView,
    TicketsByTypeView,
    TicketsOverTimeView,
)


urlpatterns = [
    path(
        "status-distribution/",
        StatusDistributionView.as_view(),
        name="reports-status-distribution",
    ),
    path(
        "tickets-over-time/",
        TicketsOverTimeView.as_view(),
        name="reports-tickets-over-time",
    ),
    path(
        "manager-throughput/",
        ManagerThroughputView.as_view(),
        name="reports-manager-throughput",
    ),
    path(
        "age-buckets/",
        AgeBucketsView.as_view(),
        name="reports-age-buckets",
    ),
    path(
        "sla-distribution/",
        SLADistributionView.as_view(),
        name="reports-sla-distribution",
    ),
    path(
        "sla-breach-rate-over-time/",
        SLABreachRateOverTimeView.as_view(),
        name="reports-sla-breach-rate-over-time",
    ),
    # ---- Sprint 5 dimensions + exports --------------------------------
    path(
        "tickets-by-type/",
        TicketsByTypeView.as_view(),
        name="reports-tickets-by-type",
    ),
    path(
        "tickets-by-type/export.csv",
        TicketsByTypeCSVView.as_view(),
        name="reports-tickets-by-type-csv",
    ),
    path(
        "tickets-by-type/export.pdf",
        TicketsByTypePDFView.as_view(),
        name="reports-tickets-by-type-pdf",
    ),
    path(
        "tickets-by-customer/",
        TicketsByCustomerView.as_view(),
        name="reports-tickets-by-customer",
    ),
    path(
        "tickets-by-customer/export.csv",
        TicketsByCustomerCSVView.as_view(),
        name="reports-tickets-by-customer-csv",
    ),
    path(
        "tickets-by-customer/export.pdf",
        TicketsByCustomerPDFView.as_view(),
        name="reports-tickets-by-customer-pdf",
    ),
    path(
        "tickets-by-building/",
        TicketsByBuildingView.as_view(),
        name="reports-tickets-by-building",
    ),
    path(
        "tickets-by-building/export.csv",
        TicketsByBuildingCSVView.as_view(),
        name="reports-tickets-by-building-csv",
    ),
    path(
        "tickets-by-building/export.pdf",
        TicketsByBuildingPDFView.as_view(),
        name="reports-tickets-by-building-pdf",
    ),
]
