# Generated by Django 5.2.14 on 2026-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_bsv_staff_completion_routes_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmanagerassignment',
            name='permission_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="B6 — per-(BM, building) override map for the two BM-revocable osius.* keys (`osius.building_manager.override_customer_decision`, `osius.building_manager.prepare_extra_work_proposal`). Setting a key to False narrows the BM's default for this building. Only Super Admin and Provider Company Admin may edit this map."),
        ),
    ]
