# Generated by Django 5.2.17 on 2026-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildingmanagerassignment_permission_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='cost_centre_code',
            field=models.CharField(blank=True, default='', help_text="The accounting code for this building as a cost centre. Free text: it is the customer's own coding scheme.", max_length=32),
        ),
        migrations.AddField(
            model_name='building',
            name='order_number',
            field=models.CharField(blank=True, default='', help_text="The customer's order or work-order number for this location, printed on the hour report.", max_length=64),
        ),
    ]
