# Generated by Django 5.2.17 on 2026-08-13 13:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_building_cost_centre_code_building_order_number'),
        ('companies', '0005_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing name, e.g. "Zorggebouw", "Kantoor".', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Archived types stay on the buildings that carry them but are not offerable for new ones.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order in the pickers; ties break on name.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Provider company that owns this building type. PROTECT mirrors HourType.company: a Company cannot be hard-deleted while it still owns building types.', on_delete=django.db.models.deletion.PROTECT, related_name='building_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'building type',
                'verbose_name_plural': 'building types',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.ForeignKey(blank=True, help_text="Optional classification from this company's own catalog.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='buildings.buildingtype'),
        ),
        migrations.AddConstraint(
            model_name='buildingtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('company'), name='uniq_building_type_name_per_company_ci'),
        ),
    ]
