# Generated by Django 5.2.17 on 2026-08-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_buildingtype_building_building_type_and_more'),
        ('customers', '0019_sprint185_customer_address_lifecycle_contact_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingCostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_pct', models.DecimalField(decimal_places=2, help_text="This customer's percentage of the building's cost, 0.01 to 100.00. The shares of one building sum to exactly 100, enforced at the write path (a sum is a condition over rows, which no database constraint can express).", max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(help_text='The shared building whose cost this row divides.', on_delete=django.db.models.deletion.CASCADE, related_name='cost_shares', to='buildings.building')),
                ('customer', models.ForeignKey(help_text="The customer carrying this share. PROTECT: removing a share-holder would silently change every other tenant's bill, so the share must be cleared deliberately first.", on_delete=django.db.models.deletion.PROTECT, related_name='building_cost_shares', to='customers.customer')),
            ],
            options={
                'verbose_name': 'building cost share',
                'verbose_name_plural': 'building cost shares',
                'ordering': ['-share_pct', 'customer_id'],
                'constraints': [models.UniqueConstraint(fields=('building', 'customer'), name='uniq_cost_share_per_building_customer'), models.CheckConstraint(condition=models.Q(('share_pct__gt', 0), ('share_pct__lte', 100)), name='cost_share_pct_between_0_and_100')],
            },
        ),
    ]
