# Generated by Django 5.2.16 on 2026-08-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slawarningthreshold',
            name='approval_cutoff_also_notify',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='approval_cutoff_extra_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='approval_cutoff_final_escalate_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='count_calendar_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='manager_review_also_notify',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='manager_review_extra_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='manager_review_final_escalate_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='not_started_also_notify',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='not_started_extra_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='not_started_final_escalate_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slawarningthreshold',
            name='weekly_summary_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
