# Generated by Django 5.2.13 on 2026-05-08 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=8)),
                ('target_model', models.CharField(help_text='"app_label.ModelName" of the mutated object.', max_length=100)),
                ('target_id', models.IntegerField(help_text='Primary key of the mutated object at the time of the event.')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Per-field diff: {"field": {"before": <old>, "after": <new>}}. Sensitive fields are stripped before write.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the mutation. NULL for system writes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
