# Generated by Django 5.2.14 on 2026-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_scope',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of the actor's role + scope anchors at write time. Shape: role / user_id / company_ids / customer_id / building_id. Empty dict for anonymous or system writes."),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Operator-supplied free text explaining a privileged mutation. Empty for legacy / system writes. Set via audit.context.set_current_reason() in the calling view.'),
        ),
    ]
