# Generated by Django 5.2.14 on 2026-06-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_reason_actor_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured business-event metadata (e.g. the dangerous event name + anchors). Empty for ordinary CRUD rows.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High / red-flag')], db_index=True, default='NORMAL', help_text='NORMAL for routine mutations; HIGH for dangerous / red-flag business events (e.g. the Extra Work quote-bypass).', max_length=8),
        ),
    ]
